"""Persistence model exports for migrations, services, and integrations."""

from app.models.domain import (
    Driver,
    DriverShift,
    LogisticsRequest,
    ManualChangeAudit,
    OptimizationRun,
    OptimizationTraceEvent,
    PlanningTask,
    RequestDateOption,
    RouteCycle,
    RouteExplanation,
    RoutePlan,
    RouteSegment,
    RouteStop,
    Scenario,
    Trailer,
    UnassignedTask,
    Vehicle,
    VehicleLoadProfile,
    VehicleLoadProfileType,
    Warehouse,
    Zone,
    ZoneRelation,
)

__all__ = [
    "Driver",
    "DriverShift",
    "LogisticsRequest",
    "ManualChangeAudit",
    "OptimizationRun",
    "OptimizationTraceEvent",
    "PlanningTask",
    "RequestDateOption",
    "RouteCycle",
    "RouteExplanation",
    "RoutePlan",
    "RouteSegment",
    "RouteStop",
    "Scenario",
    "Trailer",
    "UnassignedTask",
    "Vehicle",
    "VehicleLoadProfile",
    "VehicleLoadProfileType",
    "Warehouse",
    "Zone",
    "ZoneRelation",
]
