-- Expose task-board photo evidence as a public cabin activity without rewriting
-- existing activity rows, source facts or media ownership.

alter table public.dossier_activity
    drop constraint ck_dossier_activity_code;

alter table public.dossier_activity
    add constraint ck_dossier_activity_code check (activity_code in (
        'CABIN_CREATED','CABIN_PASSPORT_CHANGED','CABIN_STATUS_CHANGED','CABIN_WAREHOUSE_CHANGED',
        'CABIN_LOGISTICS_EFFECT_APPLIED','CABIN_COMMENT_REVISION_CHANGED','CABIN_MANUAL_NOTE_ADDED',
        'ESTIMATE_CREATED','ESTIMATE_DRAFT_CHANGED','ESTIMATE_COMPLETED','ESTIMATE_AMENDED',
        'REPAIR_CREATED','REPAIR_PLAN_CHANGED','REPAIR_QUEUED','REPAIR_STAGE_COMPLETED',
        'REPAIR_PENDING_ACCEPTANCE','REPAIR_REWORK_CREATED','REPAIR_TRANSFER_PREPARED',
        'REPAIR_TRANSFERRED','REPAIR_ACCEPTED','REPAIR_WRITTEN_OFF',
        'INVENTORY_FINDING_ADDED','INVENTORY_INSPECTION_SAVED','INVENTORY_PUBLICATION_READY',
        'INVENTORY_PUBLICATION_REQUESTED','INVENTORY_PUBLICATION_SUCCEEDED',
        'INVENTORY_PUBLICATION_TRANSIENT_FAILED','INVENTORY_PUBLICATION_BLOCKED',
        'INVENTORY_PUBLICATION_CLOSED_BLOCKED','MEDIA_READY','MEDIA_TASK_EVIDENCE_ATTACHED',
        'MEDIA_FAILED','MEDIA_ROTATED','MEDIA_DELETED'
    ));
