package dev.buhanzaz.rwms.logistics.order.domain;

public enum OrderAuditEventType {
  ORDER_CREATED,
  CLIENT_SELECTED,
  CLIENT_CREATED,
  WAREHOUSE_SELECTED,
  UNIT_ADDED,
  UNIT_ADD_CONFLICT,
  UNIT_REMOVED,
  RESERVATION_CREATED,
  RESERVATION_RELEASED,
  EQUIPMENT_ADDED,
  EQUIPMENT_INCREASED,
  EQUIPMENT_DECREASED,
  WAREHOUSE_OPERATION_CREATED,
  ORDER_CHANGED,
  ORDER_CANCELLED
}
