import { DEFAULT_PLANNING_SETTINGS, EMPTY_METRICS } from '../src/domain/defaults';
import type {
  LogisticsRequest,
  RoutePlan,
  Warehouse,
  WarehouseWorkspace,
} from '../src/domain/types';

export function warehouseFixture(overrides: Partial<Warehouse> = {}): Warehouse {
  return {
    id: 'warehouse-1',
    external_warehouse_id: '11111111-1111-4111-8111-111111111111',
    external_warehouse_version: 1,
    name: 'Склад СПб',
    city: 'Санкт-Петербург',
    address: 'Санкт-Петербург, Шоссе Революции, 1',
    timezone: 'Europe/Moscow',
    latitude: 59.961,
    longitude: 30.49,
    representative: false,
    routing_ready: true,
    default_planning_date: '2026-08-30',
    seed: 42,
    settings: { ...DEFAULT_PLANNING_SETTINGS },
    capacity_generation: 1,
    loading_minutes: 30,
    unloading_minutes: 20,
    turnaround_minutes: 20,
    working_day_start: '08:00',
    working_day_end: '20:00',
    isochrone_price_60_minutes: 10_000,
    isochrone_price_120_minutes: 15_000,
    isochrone_price_180_minutes: 20_000,
    isochrone_price_240_minutes: 25_000,
    created_at: '2026-08-24T00:00:00Z',
    updated_at: '2026-08-24T00:00:00Z',
    ...overrides,
  };
}

export function requestFixture(overrides: Partial<LogisticsRequest> = {}): LogisticsRequest {
  return {
    id: 'request-1',
    warehouse_id: 'warehouse-1',
    source_system: null,
    external_id: null,
    type: 'DELIVERY',
    name: 'Доставка 1',
    address_label: 'Санкт-Петербург, Невский проспект, 1',
    latitude: 59.935,
    longitude: 30.325,
    quantity: 2,
    trailer_access_allowed: true,
    include_driver_passport_in_notification: false,
    contact_name: 'Клиент',
    contact_phone: '+79990000000',
    service_minutes: 30,
    priority: 10,
    mandatory: false,
    status: 'READY',
    zone_id: 'zone-1',
    zone_version: 1,
    split_allowed: true,
    notes: '',
    created_at: '2026-08-24T00:00:00Z',
    updated_at: '2026-08-24T00:00:00Z',
    scheduled_date: '2026-08-30',
    date_options: [{
      date: '2026-08-30',
      priority: 1,
      window_start: '12:00',
      window_end: '15:00',
      is_hard: true,
    }],
    tasks: [{
      id: 'task-1',
      request_id: 'request-1',
      part_number: 1,
      quantity: 2,
      trailer_access_allowed: true,
      type: 'DELIVERY',
      latitude: 59.935,
      longitude: 30.325,
      zone_id: 'zone-1',
      zone_version: 1,
      service_minutes: 30,
      priority: 10,
      mandatory: false,
      status: 'READY',
    }],
    zone_status: 'CURRENT',
    ...overrides,
  };
}

export function workspaceFixture(overrides: Partial<WarehouseWorkspace> = {}): WarehouseWorkspace {
  const warehouse = overrides.warehouse ?? warehouseFixture();
  return {
    warehouse,
    warehouses: [warehouse],
    zones: [{
      id: 'zone-1',
      warehouse_id: warehouse.id,
      name: 'Зелёная зона',
      kind: 'SPECIAL_PRICE',
      color: '#20C997',
      delivery_price: 20_000,
      pickup_price: 15_000,
      geometry: {
        type: 'Polygon',
        coordinates: [[[30, 59], [31, 59], [31, 60], [30, 60], [30, 59]]],
      },
      version: 1,
      locked: false,
      created_at: '2026-08-24T00:00:00Z',
      updated_at: '2026-08-24T00:00:00Z',
    }],
    drivers: [{
      id: 'driver-1',
      warehouse_id: warehouse.id,
      external_worker_id: null,
      name: 'Водители склада',
      rwms_assignment_mode: 'WAREHOUSE_DRIVERS',
      passport_details: '',
      active: true,
      notes: '',
    }],
    vehicles: [{
      id: 'vehicle-1',
      warehouse_id: warehouse.id,
      name: 'МАЗ',
      registration_number: 'А123БВ',
      capacity: 2,
      active: true,
      average_speed_city: 35,
      average_speed_region: 65,
      notes: '',
    }],
    trailers: [],
    shifts: [{
      id: 'shift-1',
      warehouse_id: warehouse.id,
      driver_id: 'driver-1',
      vehicle_id: 'vehicle-1',
      date_from: '2026-08-01',
      date_to: '2026-08-31',
      start_time: '08:00',
      end_time: '20:00',
      break_minutes: 60,
      active: true,
    }],
    requests: [requestFixture({ warehouse_id: warehouse.id })],
    plans: [],
    ...overrides,
  };
}

export function planFixture(overrides: Partial<RoutePlan> = {}): RoutePlan {
  return {
    id: 'plan-1',
    warehouse_id: 'warehouse-1',
    date: '2026-08-30',
    version: 3,
    status: 'GENERATED',
    score: 42,
    created_at: '2026-08-24T00:00:00Z',
    updated_at: '2026-08-24T00:00:00Z',
    driver_routes: [],
    unassigned: [],
    metrics: { ...EMPTY_METRICS },
    manually_changed: false,
    ...overrides,
  };
}
