package dev.buhanzaz.rwms.logistics.service;

import java.util.UUID;

/**
 * Canonical operation names for durable document effects. Workflow relays and command owners use
 * these values as stable retry and recovery markers; this type contains no state or policy.
 */
final class LogisticsDocumentEffectOperations {
  static final String RETURN_WAREHOUSE_IDENTITY = "RETURN_WAREHOUSE_IDENTITY";
  static final String RETURN_MEDIA_OWNER_PROOF_REGISTER = "RETURN_MEDIA_OWNER_PROOF_REGISTER";
  static final String SHIPMENT_MEDIA_OWNER_PROOF_REGISTER =
      "MEDIA_SHIPMENT_OWNER_PROOF_REGISTER";
  static final String RETURN_MEDIA_VALIDATE = "RETURN_MEDIA_VALIDATE";
  static final String RETURN_ASSET_SETTLE_FREE = "RETURN_ASSET_SETTLE_FREE";
  static final String RETURN_ASSET_SETTLE_ESTIMATE = "RETURN_ASSET_SETTLE_ESTIMATE";
  static final String RETURN_ASSET_ADDITIONAL_EQUIPMENT_RECEIVE =
      "RETURN_ASSET_ADDITIONAL_EQUIPMENT_RECEIVE";
  static final String RETURN_MAINTENANCE_ESTIMATE_SOURCE_UPSERT =
      "RETURN_MAINTENANCE_ESTIMATE_SOURCE_UPSERT";
  static final String RETURN_ASSET_LEASE_RELEASE = "RETURN_ASSET_LEASE_RELEASE";
  static final String SHIPMENT_ASSET_SNAPSHOT = "SHIPMENT_ASSET_SNAPSHOT";
  static final String SHIPMENT_HISTORICAL_MAINTENANCE_CLOSE =
      "SHIPMENT_HISTORICAL_MAINTENANCE_CLOSE";
  static final String SHIPMENT_ASSET_LEASE_ACQUIRE = "SHIPMENT_ASSET_LEASE_ACQUIRE";
  static final String SHIPMENT_ASSET_CONFIRM = "SHIPMENT_ASSET_CONFIRM";
  static final String SHIPMENT_ASSET_LEASE_RELEASE = "SHIPMENT_ASSET_LEASE_RELEASE";
  static final String SHIPMENT_HOLD_ACQUIRE_PREFIX = "SHIPMENT_HOLD_ACQUIRE:";
  static final String SHIPMENT_HOLD_COMMIT_PREFIX = "SHIPMENT_HOLD_COMMIT:";
  static final String SHIPMENT_HOLD_RELEASE_PREFIX = "SHIPMENT_HOLD_RELEASE:";
  static final String TRANSFER_ORIGIN_WAREHOUSE_IDENTITY = "TRANSFER_ORIGIN_WAREHOUSE_IDENTITY";
  static final String TRANSFER_DESTINATION_WAREHOUSE_IDENTITY =
      "TRANSFER_DESTINATION_WAREHOUSE_IDENTITY";
  static final String TRANSFER_ASSET_SNAPSHOT = "TRANSFER_ASSET_SNAPSHOT";
  static final String TRANSFER_MAINTENANCE_PREPARE_DEPARTURE =
      "TRANSFER_MAINTENANCE_PREPARE_DEPARTURE";
  static final String TRANSFER_ASSET_LEASE_ACQUIRE = "TRANSFER_ASSET_LEASE_ACQUIRE";
  static final String TRANSFER_ASSET_DEPART = "TRANSFER_ASSET_DEPART";
  static final String TRANSFER_ARRIVAL_DESTINATION_WAREHOUSE_IDENTITY =
      "TRANSFER_ARRIVAL_DESTINATION_WAREHOUSE_IDENTITY";
  static final String TRANSFER_MEDIA_VALIDATE = "TRANSFER_MEDIA_VALIDATE";
  static final String TRANSFER_ASSET_ARRIVAL_SNAPSHOT = "TRANSFER_ASSET_ARRIVAL_SNAPSHOT";
  static final String TRANSFER_ASSET_ARRIVE = "TRANSFER_ASSET_ARRIVE";
  static final String TRANSFER_ASSET_LEASE_RELEASE = "TRANSFER_ASSET_LEASE_RELEASE";
  static final String TRANSFER_MAINTENANCE_COMPLETE_ARRIVAL =
      "TRANSFER_MAINTENANCE_COMPLETE_ARRIVAL";
  static final String TRANSFER_MEDIA_OWNER_PROOF_REGISTER =
      "TRANSFER_MEDIA_OWNER_PROOF_REGISTER";
  static final String TRANSFER_MEDIA_OWNER_PROOF_DEACTIVATE =
      "TRANSFER_MEDIA_OWNER_PROOF_DEACTIVATE";

  private LogisticsDocumentEffectOperations() {}

  static String holdAcquireOperation(UUID equipmentId) {
    return SHIPMENT_HOLD_ACQUIRE_PREFIX + equipmentId;
  }

  static String holdCommitOperation(UUID holdId) {
    return SHIPMENT_HOLD_COMMIT_PREFIX + holdId;
  }

  static String holdReleaseOperation(UUID holdId) {
    return SHIPMENT_HOLD_RELEASE_PREFIX + holdId;
  }
}
